- name: Ping Cisco devices and execute roles if they respond
  hosts: all_cisco_devices
  gather_facts: no
  tasks:
    - name: Ping device
      ping:

    - name: Execute roles if device is up
      when: "'SUCCESS' in ping_results.stdout"
      include_role:
        name: config_tacacs

      include_role:
        name: config_snmp

      include_role:
        name: config_syslog
        
      include_role:
        name: config_snmp_traps
        
      include_role:
        name: config_ACL1
        
      include_role:
        name: config_ACL2
        
      include_role:
        name: config_ACL3
        
      include_role:
        name: config_LLDP
        
      include_role:
        name: save_rconfig
